export enum AccountStatus {
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
  BANNED = "BANNED",
  COMPROMISED = "COMPROMISED",
  ARCHIVED = "ARCHIVED",
  UNKNOWN = "UNKNOWN",
}

export enum BookingStatus {
  REQUESTED = "REQUESTED",
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  DECLINED = "DECLINED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
}

export enum SeatType {
  REGULAR = "REGULAR",
  PREMIUM = "PREMIUM",
  ACCESSIBLE = "ACCESSIBLE",
  EMERGENCY_EXIT = "EMERGENCY_EXIT",
  VIP = "VIP",
}

export enum NotificationType {
  BOOKING_CONFIRMATION = "BOOKING_CONFIRMATION",
  BOOKING_CANCELLATION = "BOOKING_CANCELLATION",
  PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION",
  PAYMENT_REFUND = "PAYMENT_REFUND",
  NEW_MOVIE = "NEW_MOVIE",
  DISCOUNT_OFFER = "DISCOUNT_OFFER",
}
